### ISSUE TITLE
How do people feel about transferring this repo to github.com/fair-software

### ISSUE THREAD

**Issue by jspaaks** [fair-software/fair-software-frontend#26]
https://github.com/fair-software/

Not sure what it would take with respect to the netlify integration. 

Also I'm not sure having an organization-agnostic repo is a benefit or a downside. Opinions welcome.

**Comment by c-martinez** [comment]
@Tommos0 ? What would be the implications of it?

**Comment by Tommos0** [comment]
Not sure, I suppose linking the netlify account to another repo should be straight forward. I don't have any strong opinions where this repo should live. As such, I suggest we leave it where it is :).

**Comment by mkuzak** [comment]
I'm in favour of this

**Comment by c-martinez** [comment]
Yes -- @ctwhome is looking into what it takes to change netlify.

**Comment by ctwhome** [comment]
@c-martinez  I will need the account access to Netlify

**Comment by ctwhome** [comment]
I am not particularly doing anything yet. We checked with other projects how easy it would be to migrate from one place to another, the question I guess still reminds on if it's going to be moved or not.

**Comment by c-martinez** [comment]
Do I understand correctly that migrating netlify when the repo moves should be relatively easy? If yes, then let's go ahead and move the repo :-)

**Comment by ctwhome** [comment]
oke, I'll pick it up next week

**Comment by c-martinez** [comment]
Great -- ping me if you need any help :-)

**Comment by ctwhome** [comment]
@c-martinez is this still relevant?

**Comment by c-martinez** [comment]
Yes, I think it would still be good to transfer this repo to the other organisation. Hopefully without breaking netlify. Can you work your magic?

**Comment by ctwhome** [comment]
finally done, moved to @fair-software
![image](https://user-images.githubusercontent.com/4195550/106280024-a4a90700-623d-11eb-9273-8a3ea62e0623.png)

**Comment by jspaaks** [comment]
Good stuff, thanks for taking this up.
