### ISSUE TITLE
Change OG image

### ISSUE THREAD

**Issue by c-martinez** [fair-software/fair-software-frontend#66]
Slack picks [this picture](https://fair-software.eu/img/og.png) when sharing a link to https://fair-software.eu/. As discussed via email, we would like to change this image.

Perhaps the easiest is to replace this image for another one having the same text, but a [different hand](https://github.com/fair-software/fair-software-frontend/blob/master/static/img/fair_hand.svg). If this is not possible, other suggestions are welcome.

@ctwhome -- you think you might be able to do this?

**Comment by ctwhome** [comment]
Yes, I will swap it with this one:

![](https://user-images.githubusercontent.com/4195550/115560672-1af55c80-a2b5-11eb-8027-6377d0589d86.png)

**Comment by c-martinez** [comment]
Closed by #67
